theme: jekyll-theme-minimal
title: Rafael Lopes's Page
description: A simple webpage for a simples physicist
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
